name: Graal Java CI

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache : 'maven'

      - name: Build with Maven
        run: mvn clean package -Pnative

      - name: Run and validate
        run: ./target/tambola-gen${{ runner.os == 'Windows' && '.exe' || '' }} --help

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tambola-gen-${{ runner.os == 'macOS' && 'arm64' || (runner.os == 'Windows' && 'windows' || 'linux') }}
          path: ./target/tambola-gen${{ runner.os == 'Windows' && '.exe' || '' }}

      - name: Rename artifact
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mv ./target/tambola-gen${{ runner.os == 'Windows' && '.exe' || '' }} \
             ./target/tambola-gen-${{ runner.os == 'macOS' && 'arm64' || (runner.os == 'Windows' && 'windows' || 'linux') }}${{ runner.os == 'Windows' && '.exe' || '' }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: ./target/tambola-gen-*
          allowUpdates: true
          replacesArtifacts: false
          token: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6