name: Graal Java CI

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'
  pull_request:
    branches: [ "main"]

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache : 'maven'

      - name: Build with Maven
        run: mvn clean package -Pnative

      - name: Run and validate
        run: ./target/tambola-gen

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tambola-gen-${{ runner.os == 'macOS' && 'arm64' || 'linux' }}
          path: ./target/tambola-gen

      - name: Rename artifact
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mv ./target/tambola-gen \
             ./target/tambola-gen-${{ runner.os == 'macOS' && 'arm64' || 'linux' }}

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0
          name: Release v1.0.0
          artifacts: ./target/tambola-gen-*
          allowUpdates: true
          replacesArtifacts: false
          token: ${{ secrets.GITHUB_TOKEN }}